services:
  cleaner:
    image: sheets-data-cleaner:latest
    environment:
      JWT_PUBLIC_KEY_LOCATION: /run/secrets/jwt_pub
      TG_BOT_TOKEN: /run/secrets/tg_bot_token
      EMBEDDING_BASE_URL: http://similarity:5000/similarity
    secrets:
      - jwt_pub
      - tg_bot_token

secrets:
  jwt_pub:
    file: ./secrets/jwt_pub.pem
  tg_bot_token:
    file: ./secrets/tg_bot_token.txt
