spring:
  servlet:
    multipart:
      max-request-size: 8MB
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: "${JWT_PUBLIC_KEY_LOCATION}"

logging:
  level:
    mas.sheets.sheetsdatacleaner: INFO

server:
  tomcat:
    max-http-form-post-size: 8MB

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

embedding:
  api:
    base-url: ${EMBEDDING_BASE_URL:http://embedding:5000/similarity}


