global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cleaner
    metrics_path: /actuator/prometheus   # ← корректный путь
    static_configs:
      - targets: ["cleaner:8082"]

  # similarity оставляем закомментированным,
  # пока там не появится собственный энд-пойнт метрик
